apiVersion: v1
kind: Pod
metadata:
  name: tested-vault-ky-payroll
  namespace: vault
  labels:
    app: payroll
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-test: 'secret/test'
    vault.hashicorp.com/agent-inject-status: update
spec:
  serviceAccountName: vault
  containers:
    - name: payroll
      image: jweissig/app:0.0.1