apiVersion: v1
kind: Pod
metadata:
  name: netchecking-bash
  namespace: vault
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: shell-hostnet
    image: nicolaka/netshoot
    args:
    - sleep
    - infinity
